### PR TITLE
Update services.php

### PR DESCRIPTION
**Pull request by kevindykstra**

### CODE REVIEW

**Comment by tsheiner** [comment]
@kevindykstra there is still only placeholder content for decision services, i assume you want to update that, too?

**Comment by kevindykstra** [comment]
Yes, just haven't got to it yet. Will tomorrow morning early.

Sent from my iPhone

On May 1, 2016, at 6:40 PM, tsheiner <notifications@github.com<mailto:notifications@github.com>> wrote:


@kevindykstra<https://github.com/kevindykstra> there is still only placeholder content for decision services, i assume you want to update that, too?

-

**Comment by kevindykstra** [comment]
Hi Tim ... Just edited the DA and mechanistic modeling pieces. These are ready to be updated

**Comment by tsheiner** [comment]
@kevindykstra I don't see those changes in this pull request.

If you switch to this branch (kevindykstra-services-1) then you can continue editing the file and add additional commits to the same pull request. Here is a link to this branch: https://github.com/tsheiner/qpharmetra/tree/kevindykstra-services-1

**Pull request merged**
